### PR TITLE
Use MarkupSafe 2.0.1 (LTS branch)

### PR DESCRIPTION
**Pull request by agiudiceandrea**
See https://github.com/flathub/org.qgis.qgis/commit/d738b80#r67361103, flathub#174, https://github.com/flathub/org.qgis.qgis/issues/174#issuecomment-1160557294, flathub#175, pallets/markupsafe#284.

### CODE REVIEW

**Comment by aleixpol** [comment]
Have you been able to test that it fixes the issues above for you?

**Comment by rduivenvoorde** [comment]
This  issue keeps popping up on mailing lists and telegram groups. 

Any progress?

(because of somebody having this problem on Telegram, I tested it on a rather clean flatpak/debian system and had the dreaded metasearch issue on current stable flatpak: https://github.com/flathub/org.qgis.qgis/issues/211).

To test this I tried to uninstall QGIS and run build 97075...  but that is not available anymore?

```
$ flatpak uninstall org.qgis.qgis

        ID                  Branch      Op
 1. [-] org.qgis.qgis       stable      r

Uninstall complete.
$ flatpak install --user https://dl.flathub.org/build-repo/94803/org.qgis.qgis.flatpakref
error: Can't load uri https://dl.flathub.org/build-repo/94803/org.qgis.qgis.flatpakref: Server returned status 404: Not Found

```

**Comment by agiudiceandrea** [comment]
@aleixpol, after installing this build with:
`flatpak install --user https://dl.flathub.org/build-repo/99086/org.qgis.qgis.flatpakref`


running QGIS with:
`flatpak run --branch=test org.qgis.qgis`

the already reported (#174) error is displayed:
```
Couldn't load plugin 'MetaSearch' due to an error when calling its classFactory() method 

ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/lib/python3.9/site-packages/markupsafe/__init__.py) 
Traceback (most recent call last):
  File "/app/share/qgis/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/app/share/qgis/python/plugins/MetaSearch/__init__.py", line 29, in classFactory
    from MetaSearch.plugin import MetaSearchPlugin
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/MetaSearch/plugin.py", line 34, in 
    from MetaSearch.dialogs.maindialog import MetaSearchDialog
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/MetaSearch/dialogs/maindialog.py", line 61, in 
    from MetaSearch.dialogs.manageconnectionsdialog import ManageConnectionsDialog
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/MetaSearch/dialogs/manageconnectionsdialog.py", line 35, in 
    from MetaSearch.util import (get_connections_from_file, get_ui_class,
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/MetaSearch/util.py", line 38, in 
    from jinja2 import Environment, FileSystemLoader
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/lib/python3.9/site-packages/jinja2/__init__.py", line 12, in 
    from .environment import Environment
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/lib/python3.9/site-packages/jinja2/environment.py", line 25, in 
    from .defaults import BLOCK_END_STRING
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/lib/python3.9/site-packages/jinja2/defaults.py", line 3, in 
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/lib/python3.9/site-packages/jinja2/filters.py", line 13, in 
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/lib/python3.9/site-packages/markupsafe/__init__.py)


Python version: 3.9.9 (main, Nov 10 2011, 15:00:00) [GCC 11.3.0] 
QGIS version: 3.22.8-Białowieża Białowieża, exported 

Python Path:
/app/share/qgis/python
/home/andrea/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
/home/andrea/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins
/app/share/qgis/python/plugins
/usr/lib/python39.zip
/usr/lib/python3.9
/usr/lib/python3.9/lib-dynload
/usr/lib/python3.9/site-packages
/app/lib/python3.9/site-packages
/app/lib/python3.9/site-packages/MarkupSafe-2.0.1-py3.9-linux-x86_64.egg
/home/andrea/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
```


The command:
`flatpak run --devel --command=pip3 org.qgis.qgis//test list`
returns:
```
/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py:35: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Package            Version
------------------ ---------
certifi            2021.10.8
charset-normalizer 2.0.11
Cython             0.29.30
future             0.16.0
GDAL               3.4.1
idna               3.3
Jinja2             2.11.2
Mako               1.2.0
Markdown           3.3.4
MarkupSafe         2.1.1
meson              0.59.4
numpy              1.22.1
OWSLib             0.24.1
pip                22.1.1
psycopg2           2.8.6
Pygments           2.12.0
pyproj             3.3.1
PyQt5              5.15.2
PyQt5_sip          4.19.25
python-dateutil    2.8.1
pytz               2018.4
PyYAML             5.4.1
requests           2.27.1
setuptools         59.8.0
six                1.16.0
urllib3            1.26.3
wheel              0.37.1
```

The listed `MarkupSafe` package is at version 2.1.1, while such package version was explicitly pinned to 2.0.1 version. Why this happens?

**Comment by rduivenvoorde** [comment]
@agiudiceandrea you just checked, like 3 minutes ago? Because to me:

```
$ flatpak install --user https://dl.flathub.org/build-repo/99086/org.qgis.qgis.flatpakref
error: Can't load uri https://dl.flathub.org/build-repo/99086/org.qgis.qgis.flatpakref: Server returned status 404: Not Found
```

Should I add the flatpak repo first?

**Comment by agiudiceandrea** [comment]
> you just checked, like 3 minutes ago? Because to me:

I've installed it some days ago...

**Comment by agiudiceandrea** [comment]
It seems that the 2.0.1 version of Python package MarkupSafe is installed in `/app/lib/python3.9/site-packages`, but there is also the version 2.1.1 installed in `/usr/lib/python3.9/site-packages`.

```
$ flatpak run --command=sh --devel org.qgis.qgis//test
[📦 org.qgis.qgis ~]$ ls /app/lib/python3.9/site-packages
certifi				     psycopg2-2.8.6-py3.9.egg-info
certifi-2021.10.8.dist-info	     __pycache__
charset_normalizer		     pygments
charset_normalizer-2.0.11.dist-info  Pygments-2.11.2-py3.9.egg-info
dateutil			     pyproj
_distutils_hack			     pyproj-3.3.1-py3.9.egg-info
distutils-precedence.pth	     PyQt5
future				     PyQt5-5.15.2.dist-info
future-0.16.0.dist-info		     PyQt5_sip-4.19.25.dist-info
GDAL-3.4.1-py3.9.egg-info	     python_dateutil-2.8.1.dist-info
idna				     pytz
idna-3.3.dist-info		     pytz-2018.4.dist-info
jinja2				     PyYAML-5.4.1-py3.9.egg-info
Jinja2-2.11.2.dist-info		     requests
libfuturize			     requests-2.27.1.dist-info
libpasteurize			     _saga_api-8.2.3.so
markupsafe			     saga_api.py
MarkupSafe-2.0.1-py3.9.egg-info      _saga_api.so
numpy				     setuptools
numpy-1.22.1.dist-info		     setuptools-60.9.3.post20220804-py3.9.egg-info
osgeo				     sipconfig.py
osgeo_utils			     sipdistutils.py
owslib				     sip.pyi
OWSLib-0.24.1.dist-info		     urllib3
past				     urllib3-1.26.3.dist-info
pkg_resources			     _yaml
psycopg2			     yaml
[📦 org.qgis.qgis ~]$ ls /usr/lib/python3.9/site-packages
Cython			  markdown			   Pygments-2.12.0-py3.9.egg-info
Cython-0.29.30.dist-info  Markdown-3.3.4.dist-info	   pyximport
cython.py		  markupsafe			   README.txt
_distutils_hack		  MarkupSafe-2.1.1-py3.9.egg-info  setuptools
distutils-precedence.pth  meson-0.59.4.dist-info	   setuptools-59.8.0-py3.9.egg-info
drv_libxml2.py		  mesonbuild			   six-1.16.0-py3.9.egg-info
libproxy.py		  pip				   six.py
libxml2mod.so		  pip-22.1.1-py3.9.egg-info	   wheel
libxml2.py		  pkg_resources			   wheel-0.37.1-py3.9.egg-info
mako			  __pycache__			   xcbgen
Mako-1.2.0.dist-info	  pygments

```

**Comment by agiudiceandrea** [comment]
Closed in favour of https://github.com/flathub/org.qgis.qgis/pull/214.

**Pull request closed without merging**
