### PR TITLE
Ensure we are using our own proj.db

### LINKED ISSUE #221: cannot find proj.db
When running QGIS LTS installed with flatpak:

```bash
$ flatpak run --branch=lts org.qgis.qgis
proj_create_from_database: Cannot find proj.db
```

I have `PROJ_LIB=/usr/share/proj` which is a folder that does exist on the OS level, but,

```bash
$ locate proj.db
```

returns

```
/usr/share/proj/proj.db
/var/lib/flatpak/app/org.qgis.qgis/x86_64/lts/4ee848b99c0b270931a31296b40d0b4b1369de0df67297ae14b0e9046094594c/files/share/proj/proj.db
```

Among many other (miniconda) proj.db files. If I set `PROJ_LIB` to the flatpak version, nothing changes.

### PR DESCRIPTION
**Pull request by aleixpol**
Fixes #221

### CODE REVIEW

**Comment by aleixpol** [comment]
@mankoff can you give this build a go?

**Comment by mankoff** [comment]
> @mankoff <https://github.com/mankoff> can you give this build a go?
>
Yes. Can you provide a link to instructions how to install and test
specific builds?

**Comment by aleixpol** [comment]
Just like last time.

using the `flatpak install` command above and just launching QGIS.

If you are feeling uneasy about testing, I guess we can just merge, it works fine for my tests and the risk is fairly low.

**Comment by aleixpol** [comment]
Since I'm pretty sure it works, I'll just merge.

**Pull request closed without merging**
