### PR TITLE
remove 'proj.db' from proj path

### PR DESCRIPTION
**Pull request by mankoff**

### CODE REVIEW

**Comment by mankoff** [comment]
I tried to fix what I /think/ may be an issue with #224 but the build failed here too. However, not for a reason I expect or understand (i.e., the failure does not appear to have anything to do with `proj`).

**Comment by aleixpol** [comment]
I've just issued a build with a newer gdal that uses an entirely different buildsystem. Would you be able to give it a test once it's out?

**Comment by mankoff** [comment]
Yes, willing to test. How do I know when it is out? Is this `stable` or `lts`?

**Comment by aleixpol** [comment]
stable, this one as it's still unpublished I realise: https://buildbot.flathub.org/#/builders/6/builds/6774

**Comment by mankoff** [comment]
No :(

```
$ flatpak run --branch=test org.qgis.qgis
proj_create_from_database: Cannot find proj.db
proj_create_from_database: Cannot find proj.db
proj_get_authorities_from_database: Cannot find proj.db
```

**Comment by aleixpol** [comment]
I'll close the PR because it doesn't apply anymore, let's continue the conversation here: https://github.com/flathub/org.qgis.qgis/issues/221

**Pull request closed without merging**
